### ISSUE TITLE
mx image @c1xgraal output error

### ISSUE THREAD

**Issue by clevertension** [beehive-lab/Maxine-VM#12]
it is on ubuntu 16.04
but **mx image** is ok

```
Exception in thread "main" com.sun.max.vm.runtime.FatalError: MaxGraalOptions is out of sync with Graal, regenerate and refresh in IDE
	at com.sun.max.vm.runtime.FatalError.unexpected(FatalError.java:154)
	at com.sun.max.vm.runtime.FatalError.check(FatalError.java:274)
	at com.oracle.max.vm.ext.graal.MaxGraalOptions$GeneratedCodeCheckerCallback.checkGeneratedCode(MaxGraalOptions.java:152)
	at com.sun.max.vm.hosted.JavaPrototype.<init>(JavaPrototype.java:347)
	at com.sun.max.vm.hosted.JavaPrototype.initialize(JavaPrototype.java:311)
	at com.sun.max.vm.hosted.BootImageGenerator.<init>(BootImageGenerator.java:242)
	at com.sun.max.vm.hosted.BootImageGenerator.main(BootImageGenerator.java:471)
```

**Comment by zakkak** [comment]
Thank you for reporting that issue.

Please use the following patch, till the next release:
```
diff --git a/mxmaxine/commands.py b/mxmaxine/commands.py
index 9bbc2cce0e..779cf9452b 100644
--- a/mxmaxine/commands.py
+++ b/mxmaxine/commands.py
@@ -231,6 +231,8 @@ def image(args):
             if not name in configs:
                 mx.log()
                 mx.abort('Invalid image configuration: ' + name)
+            if "graal" in name:
+                systemProps += ['-ea', '-esa']
             values = configs[name].split('@')
             del args[i]
             args[i:i] = values
```

**Comment by clevertension** [comment]
thank you very much, it is ok now, so close this issue
