### ISSUE TITLE
mx image @c1xgraal-boot fails

### ISSUE THREAD

**Issue by CNAmira** [beehive-lab/Maxine-VM#13]
such as
```
main[id=1]: Compilation of com.sun.max.vm.jni.JniFunctions.GetByteArrayRegion(Pointer, JniHandle, int, int, Pointer) by Graal failed
com.oracle.graal.graph.VerificationError: is null input must be an object
	at node: 107|IsNull
	at graph: StructuredGraph:7571{com.sun.max.vm.jni.JniFunctions.GetByteArrayRegion(Pointer, JniHandle, int, int, Pointer)}
	at com.oracle.graal.graph.Node.assertTrue(Node.java:407)
	at com.oracle.graal.nodes.calc.IsNullNode.verify(IsNullNode.java:58)
	at com.oracle.graal.graph.Graph.verify(Graph.java:563)
	at com.oracle.graal.phases.BasePhase$1.run(BasePhase.java:67)
	at com.oracle.graal.debug.internal.DebugScope.executeScope(DebugScope.java:256)
	at com.oracle.graal.debug.internal.DebugScope.scope(DebugScope.java:243)
	at com.oracle.graal.debug.Debug.scope(Debug.java:139)
	at com.oracle.graal.debug.Debug.scope(Debug.java:134)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:59)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:55)
	at com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:69)
	at com.oracle.graal.phases.BasePhase$1.run(BasePhase.java:62)
	at com.oracle.graal.debug.internal.DebugScope.executeScope(DebugScope.java:256)
	at com.oracle.graal.debug.internal.DebugScope.scope(DebugScope.java:243)
	at com.oracle.graal.debug.Debug.scope(Debug.java:139)
	at com.oracle.graal.debug.Debug.scope(Debug.java:134)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:59)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:55)
	at com.oracle.graal.compiler.GraalCompiler.emitHIR(GraalCompiler.java:133)
	at com.oracle.graal.compiler.GraalCompiler$1$1.call(GraalCompiler.java:79)
	at com.oracle.graal.compiler.GraalCompiler$1$1.call(GraalCompiler.java:76)
	at com.oracle.graal.debug.internal.DebugScope.call(DebugScope.java:381)
	at com.oracle.graal.debug.internal.DebugScope.executeScope(DebugScope.java:259)
	at com.oracle.graal.debug.internal.DebugScope.scope(DebugScope.java:243)
	at com.oracle.graal.debug.Debug.scope(Debug.java:159)
	at com.oracle.graal.debug.Debug.scope(Debug.java:130)
	at com.oracle.graal.compiler.GraalCompiler$1.run(GraalCompiler.java:76)
	at com.oracle.graal.debug.internal.DebugScope.executeScope(DebugScope.java:256)
	at com.oracle.graal.debug.internal.DebugScope.scope(DebugScope.java:243)
	at com.oracle.graal.debug.Debug.scope(Debug.java:139)
	at com.oracle.graal.compiler.GraalCompiler.compileGraph(GraalCompiler.java:72)
	at com.oracle.max.vm.ext.graal.MaxGraal.compile(MaxGraal.java:492)
	at com.oracle.max.vm.ext.c1xgraal.C1XGraal.compile(C1XGraal.java:123)
	at com.sun.max.vm.compiler.target.Compilation.compile(Compilation.java:295)
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:481)
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:428)
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:381)
	at com.sun.max.vm.hosted.CompiledPrototype$2.call(CompiledPrototype.java:608)
	at com.sun.max.vm.hosted.CompiledPrototype$2.call(CompiledPrototype.java:605)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
main[id=1]: Retrying with C1X...
  [thread:18] scope: GraalCompiler
    [thread:18] scope: GraalCompiler.FrontEnd
      [thread:18] scope: GraalCompiler.FrontEnd.HighTier
        [thread:18] scope: GraalCompiler.FrontEnd.HighTier.KindRewriter
          [thread:18] scope: GraalCompiler.FrontEnd.HighTier.KindRewriter.InterceptException
          Exception occurred in scope: GraalCompiler.FrontEnd.HighTier.KindRewriter.InterceptException
          Context obj com.oracle.graal.graph.VerificationError: is null input must be an object
	at node: 446|IsNull
	at graph: StructuredGraph:7573{com.sun.max.vm.jni.JniFunctions.CallStaticObjectMethodA(Pointer, JniHandle, MethodID, Pointer)}
          Context obj com.oracle.max.vm.ext.graal.phases.MaxWordType$KindRewriterPhase@4a4571c
          Context obj com.oracle.graal.compiler.phases.HighTier@65114a16
          Context obj StructuredGraph:7573{com.sun.max.vm.jni.JniFunctions.CallStaticObjectMethodA(Pointer, JniHandle, MethodID, Pointer)}
          Use -G:+DumpOnError to enable dumping of graphs on this error
          Context obj com.oracle.max.vm.ext.graal.MaxRuntime@45fb5001
main[id=1]: Compilation of com.sun.max.vm.jni.JniFunctions.CallStaticObjectMethodA(Pointer, JniHandle, MethodID, Pointer) by Graal failed
```
I'm building on macOS with Oracle JDK 8u151 installed, `mx image` works.

**Comment by CNAmira** [comment]
`mx image @c1xgraal` fails also.
```
======================== VM Configuration ========================
Build level: PRODUCT
Reference scheme: com.sun.max.vm.reference.direct.DirectReferenceScheme
Layout scheme: com.sun.max.vm.layout.ohm.OhmLayoutScheme
Monitor scheme: com.sun.max.vm.monitor.modal.schemes.thin_inflated.ThinInflatedMonitorScheme
Heap scheme: com.sun.max.vm.heap.sequential.semiSpace.SemiSpaceHeapScheme
Run scheme: com.sun.max.vm.run.java.JavaRunScheme
Optimizing compiler: C1XGraal
Baseline compiler: T1X
JDK: 1.8.0_151
==================================================================
<Trace 1> loading: com.sun.max.vm.reference.direct
<Trace 1> loading: com.sun.max.vm.layout.ohm
<Trace 1> loading: com.sun.max.vm.heap.sequential.semiSpace
<Trace 1> loading: com.sun.max.vm.monitor.modal.schemes.thin_inflated
<Trace 1> loading: com.sun.max.vm.run.java
<Trace 1> Substitutee for private synchronized java.util.Map com.sun.max.vm.jdk.JDK_java_lang_reflect_Method.declaredAnnotations() not found - skipping
<Trace 1> Substitutee for void com.sun.max.vm.jdk.JDK_java_lang_ClassLoader_NativeLibrary.load(java.lang.String) throws java.lang.Throwable not found - skipping
<Trace 1> Substitutee for void com.sun.max.vm.jdk.JDK_java_lang_ClassLoader_NativeLibrary.unload() not found - skipping
<Trace 1> Substitutee for private synchronized java.util.Map com.sun.max.vm.jdk.JDK_java_lang_reflect_Constructor.declaredAnnotations() not found - skipping
<Trace 1> Substitutee for public static java.lang.Class[] com.sun.max.vm.jdk.JDK_java_util_ResourceBundle.getClassContext() not found - skipping
<Trace 1> Substitutee for private static void com.sun.max.vm.jdk.JDK_java_lang_invoke_MethodHandleNatives.init(java.lang.invoke.MethodType) not found - skipping
<Trace 1> Substitutee for private java.lang.String com.sun.max.vm.jdk.JDK_java_lang_Class.getGenericSignature() not found - skipping
<Trace 1> Substitutee for void com.sun.max.vm.jdk.JDK_java_lang_Class.setProtectionDomain0(java.security.ProtectionDomain) not found - skipping
<Trace 1> getAnnotations: method sun.misc.Unsafe.getUnsafe is hidden to relection
<Trace 1> Substitutee for public java.lang.Class com.sun.max.vm.jdk.JDK_sun_misc_Unsafe.defineClass(java.lang.String,byte[],int,int) not found - skipping
<Trace 1> Substitutee for private java.lang.Class com.sun.max.vm.jdk.JDK_java_lang_ClassLoader.defineClass1(java.lang.String,byte[],int,int,java.security.ProtectionDomain,java.lang.String,boolean) not found - skipping
<Trace 1> Substitutee for private java.lang.Class com.sun.max.vm.jdk.JDK_java_lang_ClassLoader.defineClass2(java.lang.String,java.nio.ByteBuffer,int,int,java.security.ProtectionDomain,java.lang.String,boolean) not found - skipping
<Trace 1> loading: com.oracle.graal.alloc
<Trace 1> loading: com.oracle.graal.amd64
<Trace 1> loading: com.oracle.graal.api
<Trace 1> loading: com.oracle.graal.api.code
<Trace 1> loading: com.oracle.graal.api.meta
<Trace 1> loading: com.oracle.graal.bytecode
<Trace 1> loading: com.oracle.graal.compiler
<Trace 1> loading: com.oracle.graal.compiler.alloc
<Trace 1> loading: com.oracle.graal.compiler.amd64
<Trace 1> loading: com.oracle.graal.compiler.gen
<Trace 1> loading: com.oracle.graal.compiler.phases
<Trace 1> loading: com.oracle.graal.compiler.target
<Trace 1> loading: com.oracle.graal.debug
<Trace 1> loading: com.oracle.graal.graph
<Trace 1> loading: com.oracle.graal.graph.iterators
<Trace 1> loading: com.oracle.graal.java
<Trace 1> loading: com.oracle.graal.java.decompiler
<Trace 1> loading: com.oracle.graal.lir
<Trace 1> loading: com.oracle.graal.lir.amd64
<Trace 1> loading: com.oracle.graal.loop
<Trace 1> loading: com.oracle.graal.nodes
<Trace 1> loading: com.oracle.graal.nodes.calc
<Trace 1> loading: com.oracle.graal.nodes.cfg
<Trace 1> loading: com.oracle.graal.nodes.debug
<Trace 1> loading: com.oracle.graal.nodes.extended
<Trace 1> loading: com.oracle.graal.nodes.java
<Trace 1> loading: com.oracle.graal.nodes.spi
<Trace 1> loading: com.oracle.graal.nodes.type
<Trace 1> loading: com.oracle.graal.nodes.util
<Trace 1> loading: com.oracle.graal.nodes.virtual
<Trace 1> loading: com.oracle.graal.phases
<Trace 1> loading: com.oracle.graal.phases.common
<Trace 1> loading: com.oracle.graal.phases.common.util
<Trace 1> loading: com.oracle.graal.phases.graph
<Trace 1> loading: com.oracle.graal.phases.schedule
<Trace 1> loading: com.oracle.graal.phases.tiers
<Trace 1> loading: com.oracle.graal.phases.util
<Trace 1> loading: com.oracle.graal.phases.verify
<Trace 1> loading: com.oracle.graal.printer
<Trace 1> loading: com.oracle.graal.replacements
<Trace 1> loading: com.oracle.graal.replacements.amd64
<Trace 1> loading: com.oracle.graal.replacements.nodes
<Trace 1> loading: com.oracle.graal.virtual
<Trace 1> loading: com.oracle.graal.virtual.phases.ea
<Trace 1> loading: com.oracle.max.asm
<Trace 1> loading: com.oracle.max.asm.target.aarch64
<Trace 1> loading: com.oracle.max.asm.target.amd64
<Trace 1> loading: com.oracle.max.asm.target.armv7
<Trace 1> loading: com.oracle.max.asm.target.riscv
<Trace 1> loading: com.oracle.max.cri
<Trace 1> loading: com.oracle.max.cri.intrinsics
<Trace 1> loading: com.oracle.max.criutils
<Trace 1> loading: com.oracle.max.vm.ext.c1x
<Trace 1> loading: com.oracle.max.vm.ext.c1xgraal
<Trace 1> loading: com.oracle.max.vm.ext.graal
<Trace 1> loading: com.oracle.max.vm.ext.graal.amd64
<Trace 1> loading: com.oracle.max.vm.ext.graal.hosted
<Trace 1> loading: com.oracle.max.vm.ext.graal.nodes
<Trace 1> loading: com.oracle.max.vm.ext.graal.phases
<Trace 1> loading: com.oracle.max.vm.ext.graal.snippets
<Trace 1> loading: com.oracle.max.vm.ext.graal.snippets.amd64
<Trace 1> loading: com.oracle.max.vm.ext.graal.snippets.hosted
<Trace 1> loading: com.oracle.max.vm.ext.graal.stubs
<Trace 1> loading: com.oracle.max.vm.ext.jjvmti
<Trace 1> loading: com.oracle.max.vm.ext.maxri
<Trace 1> loading: com.oracle.max.vm.ext.t1x
<Trace 1> loading: com.oracle.max.vm.ext.t1x.amd64
<Trace 1> loading: com.oracle.max.vm.ext.t1x.jvmti
<Trace 1> loading: com.oracle.max.vm.ext.t1x.jvmti.amd64
<Trace 1> loading: com.oracle.max.vm.ext.t1x.jvmti.armv7
<Trace 1> loading: com.sun.c1x
<Trace 1> loading: com.sun.c1x.alloc
<Trace 1> loading: com.sun.c1x.asm
<Trace 1> loading: com.sun.c1x.debug
<Trace 1> loading: com.sun.c1x.gen
<Trace 1> loading: com.sun.c1x.graph
<Trace 1> loading: com.sun.c1x.intrinsics
<Trace 1> loading: com.sun.c1x.ir
<Trace 1> loading: com.sun.c1x.lir
<Trace 1> loading: com.sun.c1x.observer
<Trace 1> loading: com.sun.c1x.opt
<Trace 1> loading: com.sun.c1x.stub
<Trace 1> loading: com.sun.c1x.target
<Trace 1> loading: com.sun.c1x.target.aarch64
<Trace 1> loading: com.sun.c1x.target.amd64
<Trace 1> loading: com.sun.c1x.target.armv7
<Trace 1> loading: com.sun.c1x.target.sparc
<Trace 1> loading: com.sun.c1x.util
<Trace 1> loading: com.sun.c1x.value
<Trace 1> loading: com.sun.cri
<Trace 1> loading: com.sun.cri.bytecode
<Trace 1> loading: com.sun.cri.ci
<Trace 1> loading: com.sun.cri.ri
<Trace 1> loading: com.sun.cri.xir
<Trace 1> loading: com.sun.max
<Trace 1> loading: com.sun.max.annotate
<Trace 1> loading: com.sun.max.atomic
<Trace 1> loading: com.sun.max.collect
<Trace 1> loading: com.sun.max.config
<Trace 1> loading: com.sun.max.config.base
<Trace 1> loading: com.sun.max.config.c1x
<Trace 1> loading: com.sun.max.config.c1xgraal
<Trace 1> loading: com.sun.max.config.graal
<Trace 1> loading: com.sun.max.config.jdk
<Trace 1> loading: com.sun.max.config.maxri
<Trace 1> loading: com.sun.max.config.test
<Trace 1> loading: com.sun.max.config.vm
<Trace 1> loading: com.sun.max.io
<Trace 1> loading: com.sun.max.lang
<Trace 1> loading: com.sun.max.memory
<Trace 1> loading: com.sun.max.platform
<Trace 1> loading: com.sun.max.profile
<Trace 1> loading: com.sun.max.program
<Trace 1> loading: com.sun.max.program.option
<Trace 1> loading: com.sun.max.unsafe
<Trace 1> loading: com.sun.max.util
<Trace 1> loading: com.sun.max.util.timer
<Trace 1> loading: com.sun.max.vm
<Trace 1> loading: com.sun.max.vm.actor
<Trace 1> loading: com.sun.max.vm.actor.holder
<Trace 1> loading: com.sun.max.vm.actor.member
<Trace 1> loading: com.sun.max.vm.bytecode
<Trace 1> loading: com.sun.max.vm.bytecode.graft
<Trace 1> loading: com.sun.max.vm.bytecode.refmaps
<Trace 1> loading: com.sun.max.vm.classfile
<Trace 1> loading: com.sun.max.vm.classfile.constant
<Trace 1> loading: com.sun.max.vm.classfile.stackmap
<Trace 1> loading: com.sun.max.vm.code
<Trace 1> loading: com.sun.max.vm.collect
<Trace 1> loading: com.sun.max.vm.compiler
<Trace 1> loading: com.sun.max.vm.compiler.deopt
<Trace 1> loading: com.sun.max.vm.compiler.deps
<Trace 1> loading: com.sun.max.vm.compiler.target
<Trace 1> loading: com.sun.max.vm.compiler.target.amd64
<Trace 1> loading: com.sun.max.vm.debug
<Trace 1> loading: com.sun.max.vm.ext.jvmti
<Trace 1> loading: com.sun.max.vm.heap
<Trace 1> loading: com.sun.max.vm.heap.debug
<Trace 1> loading: com.sun.max.vm.heap.sequential
<Trace 1> loading: com.sun.max.vm.heap.sequential.semiSpace
<Trace 1> loading: com.sun.max.vm.instrument
<Trace 1> loading: com.sun.max.vm.jdk
<Trace 1> loading: com.sun.max.vm.jdk.unix
<Trace 1> loading: com.sun.max.vm.jni
<Trace 1> loading: com.sun.max.vm.layout
<Trace 1> loading: com.sun.max.vm.layout.ohm
<Trace 1> loading: com.sun.max.vm.log
<Trace 1> loading: com.sun.max.vm.log.hosted
<Trace 1> loading: com.sun.max.vm.log.nat
<Trace 1> loading: com.sun.max.vm.log.nat.thread
<Trace 1> loading: com.sun.max.vm.log.nat.thread.var
<Trace 1> loading: com.sun.max.vm.log.nat.thread.var.std
<Trace 1> loading: com.sun.max.vm.management
<Trace 1> loading: com.sun.max.vm.methodhandle
<Trace 1> loading: com.sun.max.vm.monitor
<Trace 1> loading: com.sun.max.vm.monitor.modal
<Trace 1> loading: com.sun.max.vm.monitor.modal.modehandlers
<Trace 1> loading: com.sun.max.vm.monitor.modal.modehandlers.inflated
<Trace 1> loading: com.sun.max.vm.monitor.modal.modehandlers.lightweight
<Trace 1> loading: com.sun.max.vm.monitor.modal.modehandlers.lightweight.biased
<Trace 1> loading: com.sun.max.vm.monitor.modal.modehandlers.lightweight.thin
<Trace 1> loading: com.sun.max.vm.monitor.modal.modehandlers.observer
<Trace 1> loading: com.sun.max.vm.monitor.modal.schemes
<Trace 1> loading: com.sun.max.vm.monitor.modal.schemes.thin_inflated
<Trace 1> loading: com.sun.max.vm.monitor.modal.sync
<Trace 1> loading: com.sun.max.vm.monitor.modal.sync.nat
<Trace 1> loading: com.sun.max.vm.object
<Trace 1> loading: com.sun.max.vm.profile
<Trace 1> loading: com.sun.max.vm.profilers.sampling
<Trace 1> loading: com.sun.max.vm.reference
<Trace 1> loading: com.sun.max.vm.reference.direct
<Trace 1> loading: com.sun.max.vm.reflection
<Trace 1> loading: com.sun.max.vm.run
<Trace 1> loading: com.sun.max.vm.run.java
<Trace 1> loading: com.sun.max.vm.runtime
<Trace 1> loading: com.sun.max.vm.runtime.amd64
<Trace 1> loading: com.sun.max.vm.stack
<Trace 1> loading: com.sun.max.vm.stack.amd64
<Trace 1> loading: com.sun.max.vm.tele
<Trace 1> loading: com.sun.max.vm.test
<Trace 1> loading: com.sun.max.vm.thread
<Trace 1> loading: com.sun.max.vm.ti
<Trace 1> loading: com.sun.max.vm.type
<Trace 1> loading: com.sun.max.vm.value
<Trace 1> loading: com.sun.max.vm.verifier
<Trace 1> loading: com.sun.max.vm.verifier.types
<Trace 1> loading: java.lang
<Trace 1> loading: java.lang.ref
<Trace 1> loading: java.lang.reflect
<Trace 1> BEGIN: gatherObjects
<Trace 1>  gatherObjects: 100000
<Trace 1>  gatherObjects: 200000
<Trace 1>  gatherObjects: 300000
<Trace 1>  gatherObjects: 400000
<Trace 1>  gatherObjects: 500000
<Trace 1>  gatherObjects: 600000
<Trace 1> END:   gatherObjects: 655873 objects
<Trace 1> BEGIN: creating T1X templates from com.oracle.max.vm.ext.t1x.T1XTemplateSource
<Trace 1> END:   creating T1X templates from com.oracle.max.vm.ext.t1x.T1XTemplateSource [templates code size: 9676]  (1144ms)
<Trace 1> BEGIN: creating T1X templates for intrinsics
<Trace 1> END:   creating T1X templates for intrinsics  (87ms)
<Trace 1> BEGIN: creating T1X templates from com.oracle.max.vm.ext.t1x.jvmti.JVMTI_T1XTemplateSource
<Trace 1> END:   creating T1X templates from com.oracle.max.vm.ext.t1x.jvmti.JVMTI_T1XTemplateSource [templates code size: 3013]  (160ms)
<Trace 1> # compiler threads:4
<Trace 1> forcing compilation of method java.lang.invoke.LambdaForm.<clinit>
<Trace 1> forcing compilation of method java.lang.invoke.MethodHandleImpl$BindCaller.<clinit>
<Trace 1> forcing compilation of method java.lang.invoke.MethodHandles.<clinit>
<Trace 1> forcing compilation of method java.lang.invoke.MethodHandles$Lookup.<clinit>
<Trace 1> forcing compilation of method com.sun.max.vm.jdk.BitSetProxy.asBitSetProxy
<Trace 1> forcing compilation of method com.sun.max.vm.jdk.BitSetProxy.words
<Trace 1> forcing compilation of method com.sun.max.vm.jdk.BitSetProxy.wordsInUse
<Trace 1> forcing compilation of method java.io.File.<clinit>
<Trace 1> forcing compilation of method java.lang.invoke.MethodHandleStatics.<clinit>
<Trace 1> forcing compilation of method java.lang.invoke.InvokerBytecodeGenerator.<clinit>
<Trace 1> forcing compilation of method java.lang.invoke.LambdaForm$NamedFunction.<clinit>
<Trace 1> forcing compilation of method sun.invoke.util.ValueConversions.<clinit>
<Trace 1> forcing compilation of method java.lang.UNIXProcess.<clinit>
<Trace 1> forcing compilation of method java.lang.invoke.Invokers.<clinit>
<Trace 1> BEGIN: gatherNewClasses
<Trace 1> END:   gatherNewClasses
<Trace 1> BEGIN: processNewClasses 3770
<Trace 1> END:   processNewClasses
<Trace 1> BEGIN: compile: 1265 new methods
<Trace 1>  compiled: 200 (2568 methods)
<Trace 1>  compiled: 400 (2864 methods)
<Trace 1>  compiled: 600 (3186 methods)
<Trace 1>  compiled: 800 (3265 methods)
<Trace 1>  compiled: 1000 (3310 methods)
<Trace 1>  compiled: 1200 (3380 methods)
<Trace 1>  compiled: 1400 (3492 methods)
<Trace 1>  compiled: 1600 (3655 methods)
<Trace 1>  compiled: 1800 (3805 methods)
<Trace 1>  compiled: 2000 (4066 methods)
<Trace 1>  compiled: 2200 (4234 methods)
<Trace 1>  compiled: 2400 (4445 methods)
<Trace 1>  compiled: 2600 (4561 methods)
<Trace 1>  compiled: 2800 (4692 methods)
<Trace 1>  compiled: 3000 (4881 methods)
<Trace 1>  compiled: 3200 (5105 methods)
<Trace 1>  compiled: 3400 (5384 methods)
<Trace 1>  compiled: 3600 (5588 methods)
<Trace 1>  compiled: 3800 (5756 methods)
<Trace 1>  compiled: 4000 (6128 methods)
<Trace 1>  compiled: 4200 (6302 methods)
<Trace 1>  compiled: 4400 (6480 methods)
<Trace 1>  compiled: 4600 (6614 methods)
<Trace 1>  compiled: 4800 (6763 methods)
<Trace 1>  compiled: 5000 (6911 methods)
<Trace 1>  compiled: 5200 (7017 methods)
<Trace 1>  compiled: 5400 (7193 methods)
<Trace 1>  compiled: 5600 (7403 methods)
<Trace 1>  compiled: 5800 (7590 methods)
<Trace 1>  compiled: 6000 (8555 methods)
<Trace 1>  compiled: 6200 (8769 methods)
Error occurred while compiling com.oracle.graal.graph.NodeClass$FieldScanner.scanField(Field, Class, long): java.lang.RuntimeException: unexpected compilation failure: 
Parent chain:
    com.oracle.graal.graph.NodeClass$FieldScanner.scanField(Field, Class, long)
    which overrides com.oracle.graal.graph.FieldIntrospection$BaseFieldScanner.scanField(Field, Class, long)
    which is virtually called by com.oracle.graal.graph.FieldIntrospection$BaseFieldScanner.scan(Class)
    which is directly called by com.oracle.graal.graph.NodeClass.<init>(Class)
    which is directly called by com.oracle.graal.graph.NodeClass$Registry.make(Class)
    which is directly called by com.oracle.graal.graph.Graph$CacheEntry.equals(Object)
    which overrides java.lang.Object.equals(Object)
    which is a VM entry point
java.lang.RuntimeException: unexpected compilation failure: 
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:430)
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:381)
	at com.sun.max.vm.hosted.CompiledPrototype$2.call(CompiledPrototype.java:608)
	at com.sun.max.vm.hosted.CompiledPrototype$2.call(CompiledPrototype.java:605)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.max.vm.runtime.FatalError: Compilation of com.oracle.graal.graph.NodeClass$FieldScanner.scanField(Field, Class, long) by C1XGraal failed (final attempt)
	at com.sun.max.vm.runtime.FatalError.unexpected(FatalError.java:154)
	at com.sun.max.vm.runtime.FatalError.unexpected(FatalError.java:125)
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:501)
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:428)
	... 9 more
Caused by: java.lang.AssertionError
	at com.oracle.max.vm.ext.maxri.DebugInfo.decodeFrame(DebugInfo.java:445)
	at com.oracle.max.vm.ext.maxri.DebugInfo.decodeFrame(DebugInfo.java:489)
	at com.oracle.max.vm.ext.maxri.DebugInfo.infoAt(DebugInfo.java:387)
	at com.oracle.max.vm.ext.maxri.DebugInfo.<init>(DebugInfo.java:188)
	at com.oracle.max.vm.ext.maxri.MaxTargetMethod.init(MaxTargetMethod.java:147)
	at com.oracle.max.vm.ext.maxri.MaxTargetMethod.<init>(MaxTargetMethod.java:119)
	at com.oracle.max.vm.ext.c1x.C1X.compile(C1X.java:264)
	at com.oracle.max.vm.ext.c1xgraal.C1XGraal.compile(C1XGraal.java:119)
	at com.sun.max.vm.compiler.target.Compilation.compile(Compilation.java:295)
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:481)
	... 10 more
<Trace 1>  Total time: 49.164 seconds
Exception in thread "main" com.sun.max.vm.runtime.FatalError
	at com.sun.max.vm.runtime.FatalError.unexpected(FatalError.java:154)
	at com.sun.max.vm.runtime.FatalError$1.handle(FatalError.java:58)
	at com.sun.max.program.ProgramError.unexpected(ProgramError.java:112)
	at com.sun.max.program.ProgramError.unexpected(ProgramError.java:141)
	at com.sun.max.vm.hosted.CompiledPrototype.compileWorklist(CompiledPrototype.java:632)
	at com.sun.max.vm.hosted.CompiledPrototype.compile(CompiledPrototype.java:860)
	at com.sun.max.vm.hosted.PrototypeGenerator.createGraphPrototype(PrototypeGenerator.java:78)
	at com.sun.max.vm.hosted.PrototypeGenerator.createDataPrototype(PrototypeGenerator.java:111)
	at com.sun.max.vm.hosted.BootImageGenerator.<init>(BootImageGenerator.java:246)
	at com.sun.max.vm.hosted.BootImageGenerator.main(BootImageGenerator.java:471)
Caused by: com.sun.max.vm.runtime.FatalError: Error occurred while compiling com.oracle.graal.graph.NodeClass$FieldScanner.scanField(Field, Class, long)
	at com.sun.max.vm.runtime.FatalError.unexpected(FatalError.java:154)
	at com.sun.max.vm.runtime.FatalError$1.handle(FatalError.java:58)
	at com.sun.max.program.ProgramError.unexpected(ProgramError.java:112)
	at com.sun.max.vm.hosted.CompiledPrototype.reportCompilationError(CompiledPrototype.java:655)
	at com.sun.max.vm.hosted.CompiledPrototype.access$000(CompiledPrototype.java:57)
	at com.sun.max.vm.hosted.CompiledPrototype$2.call(CompiledPrototype.java:612)
	at com.sun.max.vm.hosted.CompiledPrototype$2.call(CompiledPrototype.java:605)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: unexpected compilation failure: 
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:430)
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:381)
	at com.sun.max.vm.hosted.CompiledPrototype$2.call(CompiledPrototype.java:608)
	... 7 more
Caused by: com.sun.max.vm.runtime.FatalError: Compilation of com.oracle.graal.graph.NodeClass$FieldScanner.scanField(Field, Class, long) by C1XGraal failed (final attempt)
	at com.sun.max.vm.runtime.FatalError.unexpected(FatalError.java:154)
	at com.sun.max.vm.runtime.FatalError.unexpected(FatalError.java:125)
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:501)
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:428)
	... 9 more
Caused by: java.lang.AssertionError
	at com.oracle.max.vm.ext.maxri.DebugInfo.decodeFrame(DebugInfo.java:445)
	at com.oracle.max.vm.ext.maxri.DebugInfo.decodeFrame(DebugInfo.java:489)
	at com.oracle.max.vm.ext.maxri.DebugInfo.infoAt(DebugInfo.java:387)
	at com.oracle.max.vm.ext.maxri.DebugInfo.<init>(DebugInfo.java:188)
	at com.oracle.max.vm.ext.maxri.MaxTargetMethod.init(MaxTargetMethod.java:147)
	at com.oracle.max.vm.ext.maxri.MaxTargetMethod.<init>(MaxTargetMethod.java:119)
	at com.oracle.max.vm.ext.c1x.C1X.compile(C1X.java:264)
	at com.oracle.max.vm.ext.c1xgraal.C1XGraal.compile(C1XGraal.java:119)
	at com.sun.max.vm.compiler.target.Compilation.compile(Compilation.java:295)
	at com.sun.max.vm.compiler.CompilationBroker.compile(CompilationBroker.java:481)
	... 10 more
```

**Comment by zakkak** [comment]
Hello @CNAmira,

Thanks for reporting this issue.
I would like to let you know that we will soon release v2.4.1 that will enable you to build the `c1xgraal` image. Note, however, that the `c1xgraal-boot` configuration is not supported and won't build even with v2.4.1.

Kind regards,
Foivos
