### ISSUE TITLE
Error will compiling on android via termux

### ISSUE THREAD

**Issue by BryleHelll** [beehive-lab/Maxine-VM#25]
```Traceback (most recent call last):                  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink                                                ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.9/lib-dynload/_multiprocessing.cpython-39.so)                                            
During handling of the above exception, another exception occurred:
                                                  Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/stuffs/maxine-src/mx/mx.py", line 16700, in <module>            __compile_mx_class_lock = multiprocessing.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock                   File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```
Do i need to do it on a java IDE's terminal

**Comment by BryleHelll** [comment]
Oh its a known issue in termux, closing
