### ISSUE TITLE
mx inspect fails

### ISSUE THREAD

**Issue by Buenbk** [beehive-lab/Maxine-VM#29]
### mx inspect -cp com.oracle.max.tests/bin test.output.GCTest2

TeleWarning: Class path entry is neither a directory nor a JAR file: com.oracle.max.tests/bin  
**Error converting MAX_AGENT_PID value "3268" to a long value: No such file or directory**
**Exception in thread "main" com.sun.max.tele.util.TeleError: Tele Internal Error: failed to instantiate com.sun.max.tele.debug.linux.LinuxTeleVM**
	at com.sun.max.tele.util.TeleError.error(TeleError.java:36)
	at com.sun.max.tele.util.TeleError.unexpected(TeleError.java:47)
	at com.sun.max.tele.TeleVM.create(TeleVM.java:546)
	at com.sun.max.tele.TeleVM.create(TeleVM.java:440)
	at com.sun.max.ins.MaxineInspector.main(MaxineInspector.java:75)
**Caused by: java.lang.reflect.InvocationTargetException**
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.sun.max.tele.TeleVM.create(TeleVM.java:544)
	... 2 more
**Caused by: com.sun.max.tele.util.TeleError: Tele Internal Error: Error while reading boot image address from VM process**
	at com.sun.max.tele.util.TeleError.error(TeleError.java:36)
	at com.sun.max.tele.util.TeleError.unexpected(TeleError.java:47)
	at com.sun.max.tele.debug.unix.UnixNativeTeleChannelProtocolAdaptor.getBootHeapStart(UnixNativeTeleChannelProtocolAdaptor.java:107)
	at com.sun.max.tele.TeleVM.loadBootImage(TeleVM.java:1359)
	at com.sun.max.tele.TeleVM.<init>(TeleVM.java:807)
	at com.sun.max.tele.debug.linux.LinuxTeleVM.<init>(LinuxTeleVM.java:41)
	... 7 more
**Caused by: com.sun.max.vm.hosted.BootImageException: Timed out while waiting for connection from VM**
	at com.sun.max.tele.TeleVMAgent.waitForVM(TeleVMAgent.java:111)
	at com.sun.max.tele.debug.unix.UnixNativeTeleChannelProtocolAdaptor.getBootHeapStart(UnixNativeTeleChannelProtocolAdaptor.java:98)
	... 10 more

**Comment by kotselidis** [comment]
Hi,

The Maxine Inspector has not been supported since v2.0.
Maybe if you checkout v2.0 it may work
