### ISSUE TITLE
"mx image" fails (solved)

### ISSUE THREAD

**Issue by markshank** [beehive-lab/Maxine-VM#4]
export WORKDIR=/home/mds/max
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export MAXINE_HOME=$WORKDIR/maxine
export PATH=$PATH:$WORKDIR/graal/mxtool/:$MAXINE_HOME/com.oracle.max.vm.native/generated/linux/

$ cd $MAXINE_HOME
$ mx image
Exception in thread "main" com.sun.max.program.ProgramError: Unexpected Program Error: Class java.lang.Class does not declare field declaredFields
	at com.sun.max.program.ProgramError.unexpected(ProgramError.java:117)
	at com.sun.max.program.ProgramError.unexpected(ProgramError.java:129)
	at com.sun.max.vm.hosted.JDKInterceptor$InterceptedField.ensureFieldExists(JDKInterceptor.java:586)
	at com.sun.max.vm.hosted.JDKInterceptor$InterceptedField.verify(JDKInterceptor.java:576)
	at com.sun.max.vm.hosted.JDKInterceptor.fillInterceptedFieldMap(JDKInterceptor.java:489)
	at com.sun.max.vm.hosted.JDKInterceptor.buildInterceptedFieldMap(JDKInterceptor.java:440)
	at com.sun.max.vm.hosted.JDKInterceptor.<clinit>(JDKInterceptor.java:390)
	at com.sun.max.vm.hosted.Prototype.loadLibrary(Prototype.java:89)
	at com.sun.max.vm.hosted.Prototype.loadHostedLibrary(Prototype.java:102)
	at com.sun.max.platform.Platform.hasIDiv(Platform.java:433)
	at com.sun.max.platform.Platform.createTarget(Platform.java:176)
	at com.sun.max.platform.Platform.<init>(Platform.java:273)
	at com.sun.max.platform.Platform.<init>(Platform.java:257)
	at com.sun.max.platform.Platform.<clinit>(Platform.java:526)
	at com.sun.max.vm.hosted.VMConfigurator.defaultLayoutScheme(VMConfigurator.java:112)
	at com.sun.max.vm.hosted.VMConfigurator.<init>(VMConfigurator.java:51)
	at com.sun.max.vm.hosted.BootImageGenerator.<init>(BootImageGenerator.java:206)
	at com.sun.max.vm.hosted.BootImageGenerator.main(BootImageGenerator.java:471)
$

**Comment by zakkak** [comment]
Hello,

Could you please include the JDK version you are using to build maxine-VM?

Please refer to https://github.com/beehive-lab/Maxine-VM#platform for the currently supported platform configurations.

If you are familiar with docker you can also use our [dockerfile](https://github.com/beehive-lab/Maxine-Dockerfile) and follow the instructions to create a docker container with the appropriate configuration to build maxine-VM.

**Comment by markshank** [comment]
openjdk-7-jdk/trusty-updates,trusty-security,now 7u121-2.6.8-1ubuntu0.14.04.3 amd64 [installed]
openjdk-7-jre/trusty-updates,trusty-security,now 7u121-2.6.8-1ubuntu0.14.04.3 amd64 [installed]

**Comment by zakkak** [comment]
Unfortunately, u121 is not supported yet please try using u25.

**Comment by markshank** [comment]
Yes, u25 works for me.

**Comment by arodchen** [comment]
It would be nice to add the JDK class library version check during the build with meaningful output.

**Comment by lgeek** [comment]
Regarding the title, it actually has the same behavior on AArch32 as well.
